# Generated by Django 6.1.1 on 2026-09-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(blank=True, default='', max_length=128)),
                ('customer', models.CharField(blank=True, default='', max_length=255)),
                ('fingerprint_expected', models.CharField(blank=True, default='', max_length=128)),
                ('raw_license', models.JSONField(blank=True, default=dict)),
                ('valid', models.BooleanField(default=False)),
                ('in_grace', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Состояние лицензии',
            },
        ),
    ]
