# Generated by Django 6.1.1 on 2026-09-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('nvd', 'NVD'), ('kev', 'CISA KEV'), ('bdu', 'БДУ ФСТЭК')], max_length=16, unique=True)),
                ('status', models.CharField(default='idle', max_length=32)),
                ('checkpoint', models.CharField(blank=True, default='', max_length=255)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('items_total', models.PositiveIntegerField(default=0)),
                ('items_synced', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('record_type', models.CharField(choices=[('cve', 'CVE'), ('bdu', 'BDU'), ('local', 'LOCAL')], default='cve', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('description_nvd', models.TextField(blank=True, default='')),
                ('description_bdu', models.TextField(blank=True, default='')),
                ('severity', models.CharField(blank=True, default='', max_length=16)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_v31', models.JSONField(blank=True, default=dict)),
                ('cvss_v30', models.JSONField(blank=True, default=dict)),
                ('cvss_v2', models.JSONField(blank=True, default=dict)),
                ('cvss_v40', models.JSONField(blank=True, default=dict)),
                ('cwe', models.JSONField(blank=True, default=list)),
                ('cpe', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('in_kev', models.BooleanField(db_index=True, default=False)),
                ('kev_data', models.JSONField(blank=True, default=dict)),
                ('bdu_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('has_bdu', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('raw_nvd', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Уязвимость',
                'verbose_name_plural': 'Уязвимости',
                'ordering': ['-modified_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=16)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('prefix', 'year')},
            },
        ),
    ]
