# Generated by Django 6.1.1 on 2026-09-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_completed', models.BooleanField(default=False)),
                ('setup_step', models.PositiveSmallIntegerField(default=1)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('local_id_prefix', models.CharField(blank=True, default='ACME', max_length=16)),
                ('product_name', models.CharField(default='VULNDB', max_length=64)),
                ('login_title', models.CharField(blank=True, default='Управление уязвимостями в одном контуре', max_length=255)),
                ('login_text', models.TextField(blank=True, default='Каталог NVD / KEV / БДУ, локальные уязвимости с вашим префиксом ID, заявки на устранение и контроль лицензии.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('nvd_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('nvd_enabled', models.BooleanField(default=True)),
                ('kev_enabled', models.BooleanField(default=True)),
                ('bdu_enabled', models.BooleanField(default=True)),
                ('sync_cron_hint', models.CharField(blank=True, default='hourly', max_length=64)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_from', models.CharField(blank=True, default='', max_length=255)),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('db_host', models.CharField(blank=True, default='127.0.0.1', max_length=255)),
                ('db_port', models.PositiveIntegerField(default=5432)),
                ('db_name', models.CharField(blank=True, default='vulndb', max_length=128)),
                ('db_user', models.CharField(blank=True, default='vulndb', max_length=128)),
                ('db_sslmode', models.CharField(blank=True, default='prefer', max_length=16)),
                ('db_configured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Системные настройки',
                'verbose_name_plural': 'Системные настройки',
            },
        ),
    ]
