# Generated by Django 5.1.15 on 2026-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auth_google_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_google_client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_google_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_ldap_base_dn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_ldap_bind_dn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_ldap_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_ldap_server',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_local_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_lockout_attempts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_mfa_recommended',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_sso_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_sso_client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_sso_discovery_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_sso_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_sso_provider',
            field=models.CharField(blank=True, default='oidc', help_text='oidc | azure_ad | saml', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auth_sso_tenant',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bdu_sync_interval_minutes',
            field=models.PositiveIntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bdu_verify_ssl',
            field=models.BooleanField(default=False, help_text='Сертификат ФСТЭК часто требует отключения verify в лаборатории'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bdu_xlsx_url',
            field=models.URLField(blank=True, default='https://bdu.fstec.ru/files/documents/vullist.xlsx'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='exchange_domain',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='exchange_ews_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='kev_sync_interval_minutes',
            field=models.PositiveIntegerField(default=360),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='mail_provider',
            field=models.CharField(default='smtp', help_text='smtp | exchange | office365 | gmail', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='nvd_sync_interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sync_cron_hint',
            field=models.CharField(blank=True, default='custom', max_length=64),
        ),
    ]
